using System;
using System.IO;
using System.IO.Compression;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;

namespace VenEl.ModularMCP.Core
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var currentDir = Directory.GetCurrentDirectory();
            var pluginDir = Path.GetFullPath(Path.Combine(currentDir, "plugins"));

            // CLI Command Parsing
            if (args.Length >= 3 && args[0].Equals("plugin", StringComparison.OrdinalIgnoreCase) && args[1].Equals("install", StringComparison.OrdinalIgnoreCase))
            {
                var pluginName = args[2];
                await InstallPluginAsync(pluginName, pluginDir);
                return;
            }

            Console.Error.WriteLine("Starting VenEl.ModularMCP Core Host...");
            
            var pluginManager = new PluginManager();
            
            Console.Error.WriteLine($"Scanning for dynamic plugins in: {pluginDir}");
            var plugins = pluginManager.LoadPlugins(pluginDir);
            Console.Error.WriteLine($"Engine loaded {plugins.Count} plugins successfully.");
            
            // Setup Configuration
            var configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                // .AddJsonFile("appsettings.json", optional: true)
                .Build();

            // Setup DI Services
            var services = new ServiceCollection();
            
            foreach (var plugin in plugins)
            {
                Console.Error.WriteLine($"Configuring Services for: {plugin.Name} ({plugin.Description})");
                plugin.ConfigureServices(services, configuration);
            }
            
            var serviceProvider = services.BuildServiceProvider();
            Console.Error.WriteLine("Dependency Injection container built successfully.");
            
            foreach (var plugin in plugins)
            {
                Console.Error.WriteLine($"Initializing: {plugin.Name}");
                await plugin.InitializeAsync();
            }
            
            Console.Error.WriteLine("Core is running and waiting for MCP connections...");
        }

        static async Task InstallPluginAsync(string pluginName, string pluginDir)
        {
            Console.Error.WriteLine($"Installing plugin: {pluginName}...");
            
            // For now, assume it's fetching from our local packages folder generated by dotnet pack
            var packageName = $"VenEl.ModularMCP.{pluginName}.1.0.0.nupkg";
            var packagePath = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "..", "..", "packages", packageName));

            if (!File.Exists(packagePath))
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.Error.WriteLine($"[Error] Could not find local package at: {packagePath}");
                Console.Error.WriteLine("Run 'dotnet pack' to generate it first.");
                Console.ResetColor();
                return;
            }

            if (!Directory.Exists(pluginDir))
            {
                Directory.CreateDirectory(pluginDir);
            }

            // Target extraction directory inside plugins folder
            var targetDir = Path.Combine(pluginDir, pluginName);
            if (Directory.Exists(targetDir)) 
            {
                Directory.Delete(targetDir, true);
            }
            Directory.CreateDirectory(targetDir);

            // Open the .nupkg (which is just a zip archive)
            using (var archive = ZipFile.OpenRead(packagePath))
            {
                foreach (var entry in archive.Entries)
                {
                    // We only want to extract the DLLs from the lib/net8.0/ folder
                    if (entry.FullName.StartsWith("lib/net8.0/") && !string.IsNullOrEmpty(entry.Name))
                    {
                        var destinationPath = Path.Combine(targetDir, entry.Name);
                        entry.ExtractToFile(destinationPath, true);
                        Console.Error.WriteLine($"  -> Extracted: {entry.Name}");
                    }
                }
            }

            Console.ForegroundColor = ConsoleColor.Green;
            Console.Error.WriteLine($"\n[Success] Successfully installed '{pluginName}' into {targetDir}");
            Console.Error.WriteLine("It will be dynamically loaded the next time you boot the Core host.");
            Console.ResetColor();
        }
    }
}
