<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VenEl.ModularMCP.Shared\VenEl.ModularMCP.Shared.csproj" />
    <PackageReference Include="VenEl.MCP.GCP" Version="1.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>VenEl.ModularMCP.GCP</PackageId>
    <Version>1.0.3</Version>
    <Authors>VenEl</Authors>
    <Description>VenEl Modular MCP Plugin - VenEl.ModularMCP.GCP</Description>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
